### ISSUE TITLE
Character Randomizer dont make Oxide appear.

### ISSUE THREAD

**Issue by sebastian926** [CTR-tools/CTR-ModSDK#21]
The rest of the characters appears without any problems. But for some reason Oxide never shows, not matter the amount of times one tries.

**Comment by Superstarxalien** [comment]
This is intentional behavior for the CharacterRandomizer mod. The idea was to select CPUs from every ordinary racer character, which Oxide is not as he is twice as big and has the quirk of starting early on all races. You can go to the CTR-tools Discord server (pinned in @CTR-tools profile) and request a version of the mod that does allow for Oxide to appear as a CPU.
